### ISSUE TITLE
research clearmash photoUnits convert processor error (JSONDecodeError: Expecting value)

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/mojp-dbs-pipelines#40]
error appeared in dashboard for clearmash photoUnits convert processor:
```
datapackage_pipelines_mojp.clearmash.processors.download: Traceback (most recent call last):
datapackage_pipelines_mojp.clearmash.processors.download:   File "/mojp/datapackage_pipelines_mojp/clearmash/processors/download.py", line 59, in 
datapackage_pipelines_mojp.clearmash.processors.download:     ClearmashDownloadProcessor.main()
datapackage_pipelines_mojp.clearmash.processors.download:   File "/mojp/datapackage_pipelines_mojp/common/processors/base_processors.py", line 23, in main
datapackage_pipelines_mojp.clearmash.processors.download:     spew(*cls(*ingest()).spew())
datapackage_pipelines_mojp.clearmash.processors.download:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 59, in spew
datapackage_pipelines_mojp.clearmash.processors.download:     for rec in res:
datapackage_pipelines_mojp.clearmash.processors.download:   File "/mojp/datapackage_pipelines_mojp/clearmash/processors/download.py", line 27, in _download
datapackage_pipelines_mojp.clearmash.processors.download:     for item in clearmash_api.get_web_document_system_folder(folder_id)["Items"]:
datapackage_pipelines_mojp.clearmash.processors.download:   File "/mojp/datapackage_pipelines_mojp/clearmash/api.py", line 69, in get_web_document_system_folder
datapackage_pipelines_mojp.clearmash.processors.download:     "FolderType": FOLDER_TYPE_WebDocumentSystemFolder})
datapackage_pipelines_mojp.clearmash.processors.download:   File "/mojp/datapackage_pipelines_mojp/clearmash/api.py", line 77, in _wcm_api_call
datapackage_pipelines_mojp.clearmash.processors.download:     post_data=post_data)
datapackage_pipelines_mojp.clearmash.processors.download:   File "/mojp/datapackage_pipelines_mojp/clearmash/api.py", line 85, in _get_request_json
datapackage_pipelines_mojp.clearmash.processors.download:     return res.json()
datapackage_pipelines_mojp.clearmash.processors.download:   File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 886, in json
datapackage_pipelines_mojp.clearmash.processors.download:     return complexjson.loads(self.text, **kwargs)
datapackage_pipelines_mojp.clearmash.processors.download:   File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
datapackage_pipelines_mojp.clearmash.processors.download:     return _default_decoder.decode(s)
datapackage_pipelines_mojp.clearmash.processors.download:   File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
datapackage_pipelines_mojp.clearmash.processors.download:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
datapackage_pipelines_mojp.clearmash.processors.download:   File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
datapackage_pipelines_mojp.clearmash.processors.download:     raise JSONDecodeError("Expecting value", s, err.value) from None
datapackage_pipelines_mojp.clearmash.processors.download: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by OriHoch** [comment]
looks like it's due to photoUnits folder having too many items, and it only happens occasionally

opened a question for clearmash about it, will continue working on it there - #43 

also, added logging of clearmash API calls, so it will help to debug this problem if it happens again
