### ISSUE TITLE
clearmash download processor should not fail on Object of type 'ClearmashRelatedDocuments' is not JSON serializable

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/mojp-dbs-pipelines#59]
### reproduction
* run the pipelines
* e.g. `dpp run ./clearmash-movies`

#### expected
* pipelines should run

#### actual
* exception
```python
datapackage_pipelines_mojp.clearmash.processors.download: INFO:api:_get_request_json(https://bh.clearmash.com/API/V5/Services/WebContentManagement.svc/Documents/Get, {'entitiesIds': [115318, 115323, 115348, 115358, 115364, 115389, 115429, 115431, 115433, 115437, 115453]})
datapackage_pipelines_mojp.clearmash.processors.download: Traceback (most recent call last):
datapackage_pipelines_mojp.clearmash.processors.download:   File "/mojp/datapackage_pipelines_mojp/clearmash/processors/download.py", line 70, in 
datapackage_pipelines_mojp.clearmash.processors.download:     ClearmashDownloadProcessor.main()
datapackage_pipelines_mojp.clearmash.processors.download:   File "/mojp/datapackage_pipelines_mojp/common/processors/base_processors.py", line 25, in main
datapackage_pipelines_mojp.clearmash.processors.download:     spew(*cls(*ingest()).spew())
datapackage_pipelines_mojp.clearmash.processors.download:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 62, in spew
datapackage_pipelines_mojp.clearmash.processors.download:     ensure_ascii=True)
datapackage_pipelines_mojp.clearmash.processors.download:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/utilities/extended_json.py", line 100, in _dumpl
datapackage_pipelines_mojp.clearmash.processors.download:     return _json.dumps(*args, **kwargs)
datapackage_pipelines_mojp.clearmash.processors.download:   File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
datapackage_pipelines_mojp.clearmash.processors.download:     **kw).encode(obj)
datapackage_pipelines_mojp.clearmash.processors.download:   File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
datapackage_pipelines_mojp.clearmash.processors.download:     chunks = self.iterencode(o, _one_shot=True)
datapackage_pipelines_mojp.clearmash.processors.download:   File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
datapackage_pipelines_mojp.clearmash.processors.download:     return _iterencode(o, 0)
datapackage_pipelines_mojp.clearmash.processors.download:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/utilities/extended_json.py", line 88, in default
datapackage_pipelines_mojp.clearmash.processors.download:     return super().default(obj)
datapackage_pipelines_mojp.clearmash.processors.download:   File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
datapackage_pipelines_mojp.clearmash.processors.download:     o.__class__.__name__)
datapackage_pipelines_mojp.clearmash.processors.download: TypeError: Object of type 'ClearmashRelatedDocuments' is not JSON serializable
```

**Comment by OriHoch** [comment]
@Libisch the last deploy caused pipelines to stop working
errors can be seen on pipelines dashboard: http://devapi.dbs.bh.org.il:5000/
it reproduces locally as well

I think it's a small change, I'll fix it

**Comment by OriHoch** [comment]
fixed and deployed to dev
